source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
# gem 'spring',        group: :development
gem 'bootstrap3-rails'
gem 'bootstrap-sass-rails', '~> 2.2.2.0'
gem 'devise'
gem 'jquery-tokeninput-rails'
#gem'activeadmin', :git => 'https://github.com/gregbell/active_admin.git'
gem 'activeadmin', '~> 1.0.0.pre1'
gem 'paperclip', '~> 3.0'
gem 'bootstrap-material-design'
gem 'jquery-ui-rails'
gem 'paper_trail'
gem 'diffy'

gem 'pry-rails', :group => :development

group :development do
	gem 'better_errors'
	#for chrome plugin 'rails plugin'
	gem 'meta_request' #chrome extension: http://goo.gl/hM1ekO 
	gem 'binding_of_caller' #provides alive shell on error page
end

#group :test do
  #gem 'cucumber'
  #gem 'cucumber-rails'  
  #gem 'database_cleaner'
  #gem 'rspec'
  #gem 'rspec-rails'
  #gem 'webrat'
#end

group :test do
  gem 'cucumber-rails', :require => false
  gem 'selenium-webdriver'
  # database_cleaner is not required, but highly recommended
  gem 'database_cleaner'
  gem 'factory_girl'
  gem 'launchy'
  gem 'rspec-rails'
end

gem 'will_paginate'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

